
# See: https://github.com/TypistTech/tiller-circleci
---
version: 2
jobs:
  build:
    docker:
      - image: benword/ubuntu16.04-ansible2.5.3-nvm-yarn:0.0.1
    steps:
      - run: sudo apt-get install libpng-dev -y --no-install-recommends
      - checkout
      - run: cd site/web/app/themes/pixelize && yarn && yarn build && yarn build:production
  deploy-staging:
    docker:
      - image: benword/ubuntu16.04-ansible2.5.3-nvm-yarn:0.0.1
    environment:
      ANSIBLE_HOST_KEY_CHECKING: false
      SITE_ENV: staging
      SITE_KEY: tinypixel.io
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5e:d5:c5:af:1b:ef:9e:72:67:5b:cf:f5:87:51:9f:da"
      - restore_cache:
          key: v1-ansible-galaxy-{{ checksum "trellis/requirements.yml" }}
      - run:
          name: Set Ansible Vault Pass
          command: echo $ANSIBLE_VAULT_PASSWORD > .vault_pass
          working_directory: trellis
      - run:
          name: Install Ansible Galaxy Roles
          command: ansible-galaxy install -r requirements.yml -vvvv
          working_directory: trellis
      - deploy:
          command: ansible-playbook deploy.yml -e env=$SITE_ENV -e site=$SITE_KEY -vvvv
          working_directory: trellis
  deploy-production:
    docker:
      - image: itinerisltd/tiller:latest
    environment:
      ANSIBLE_HOST_KEY_CHECKING: false
      SITE_ENV: production
      SITE_KEY: tinypixel.io
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5e:d5:c5:af:1b:ef:9e:72:67:5b:cf:f5:87:51:9f:da"
      - restore_cache:
          key: v1-ansible-galaxy-{{ checksum "trellis/requirements.yml" }}
      - run:
          name: Set Ansible Vault Pass
          command: echo $ANSIBLE_VAULT_PASSWORD > .vault_pass
          working_directory: trellis
      - run:
          name: Install Ansible Galaxy Roles
          command: ansible-galaxy install -r requirements.yml -vvvv
          working_directory: trellis
      - deploy:
          command: ansible-playbook deploy.yml -e env=$SITE_ENV -e site=$SITE_KEY -vvvv
          working_directory: trellis
workflows:
  version: 2
  tiller:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: development
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: master
